tasks:
  - command: |
      echo "Running the command script"
      mkdir -p /workspace/.dbt
      ln -snf /workspace/.dbt ~/.dbt
      unset PROMPT_COMMAND
ports:
  - port: 8000
    onOpen: open-browser
  - port: 8081
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
