name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  course_advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false
  course_advanced_dbt:
    unit_testing:
      +schema: unit_testing
      +tags: unit_testing
      dim_dates_full:
        +column_types:
          CALENDAR_DATE: date
          DATE_WEEK: date
          DATE_MONTH: date
          DATE_QUARTER: date
          DATE_YEAR: date
          DAY_OF_MONTH: integer
          YEAR_NUM: integer
          QUARTER_NUM: integer
          MONTH_NUM: integer
      dim_subscriptions_sample:
        +column_types:
          SUBSCRIPTION_ID: integer
          SUBSCRIPTION_PLAN_ID: integer
          USER_ID: integer
          STARTS_AT: datetime
          ENDS_AT: datetime
          PLAN_NAME: varchar
          PRICING: integer
          BILLING_PERIOD: varchar
      unit_test_results:
        +column_types:
          SURROGATE_KEY: varchar
          DATE_MONTH: date
          USER_ID: integer
          SUBSCRIPTION_ID: int
          STARTS_AT: datetime
          ENDS_AT: datetime
          PLAN_NAME: varchar
          MRR_AMOUNT: int
          MRR_CHANGE: int
          RETAINED_MRR_AMOUNT: int
          PREVIOUS_MONTH_MRR_AMOUNT: int
          CHANGE_CATEGORY: varchar
          MONTH_RETAINED_NUMBER: int


vars:
  exclude_paths_from_project: ["/marts/core/fct_events.sql"]

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
